# Generated by Django 5.2.8 on 2025-11-23 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogo',
            name='contenido',
        ),
    ]
