# Generated by Django 5.2.8 on 2025-11-23 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_catalogo_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/'),
        ),
    ]
