# Generated by Django 5.2.7 on 2025-11-28 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_catalogo_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogo',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
    ]
